//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nostradamus8.NostraSrv {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalRecordBase", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Nostradamus8.NostraSrv.DisplayPersonalRecord))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Nostradamus8.NostraSrv.PersonalRecord))]
    public partial class PersonalRecordBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Additional_hoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Nostradamus8.NostraSrv.CityData BirthPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Birth_DayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Birth_Hour_FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Birth_Hour_ToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Birth_Min_FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Birth_Min_ToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Birth_MonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Birth_Sec_FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Birth_Sec_ToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Birth_YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DataTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_contributorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Second_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Additional_hours {
            get {
                return this.Additional_hoursField;
            }
            set {
                if ((this.Additional_hoursField.Equals(value) != true)) {
                    this.Additional_hoursField = value;
                    this.RaisePropertyChanged("Additional_hours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Nostradamus8.NostraSrv.CityData BirthPlace {
            get {
                return this.BirthPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthPlaceField, value) != true)) {
                    this.BirthPlaceField = value;
                    this.RaisePropertyChanged("BirthPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Birth_Day {
            get {
                return this.Birth_DayField;
            }
            set {
                if ((this.Birth_DayField.Equals(value) != true)) {
                    this.Birth_DayField = value;
                    this.RaisePropertyChanged("Birth_Day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Birth_Hour_From {
            get {
                return this.Birth_Hour_FromField;
            }
            set {
                if ((this.Birth_Hour_FromField.Equals(value) != true)) {
                    this.Birth_Hour_FromField = value;
                    this.RaisePropertyChanged("Birth_Hour_From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Birth_Hour_To {
            get {
                return this.Birth_Hour_ToField;
            }
            set {
                if ((this.Birth_Hour_ToField.Equals(value) != true)) {
                    this.Birth_Hour_ToField = value;
                    this.RaisePropertyChanged("Birth_Hour_To");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Birth_Min_From {
            get {
                return this.Birth_Min_FromField;
            }
            set {
                if ((this.Birth_Min_FromField.Equals(value) != true)) {
                    this.Birth_Min_FromField = value;
                    this.RaisePropertyChanged("Birth_Min_From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Birth_Min_To {
            get {
                return this.Birth_Min_ToField;
            }
            set {
                if ((this.Birth_Min_ToField.Equals(value) != true)) {
                    this.Birth_Min_ToField = value;
                    this.RaisePropertyChanged("Birth_Min_To");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Birth_Month {
            get {
                return this.Birth_MonthField;
            }
            set {
                if ((this.Birth_MonthField.Equals(value) != true)) {
                    this.Birth_MonthField = value;
                    this.RaisePropertyChanged("Birth_Month");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Birth_Sec_From {
            get {
                return this.Birth_Sec_FromField;
            }
            set {
                if ((this.Birth_Sec_FromField.Equals(value) != true)) {
                    this.Birth_Sec_FromField = value;
                    this.RaisePropertyChanged("Birth_Sec_From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Birth_Sec_To {
            get {
                return this.Birth_Sec_ToField;
            }
            set {
                if ((this.Birth_Sec_ToField.Equals(value) != true)) {
                    this.Birth_Sec_ToField = value;
                    this.RaisePropertyChanged("Birth_Sec_To");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Birth_Year {
            get {
                return this.Birth_YearField;
            }
            set {
                if ((this.Birth_YearField.Equals(value) != true)) {
                    this.Birth_YearField = value;
                    this.RaisePropertyChanged("Birth_Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DataType {
            get {
                return this.DataTypeField;
            }
            set {
                if ((this.DataTypeField.Equals(value) != true)) {
                    this.DataTypeField = value;
                    this.RaisePropertyChanged("DataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_contributor {
            get {
                return this.ID_contributorField;
            }
            set {
                if ((this.ID_contributorField.Equals(value) != true)) {
                    this.ID_contributorField = value;
                    this.RaisePropertyChanged("ID_contributor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Second_Name {
            get {
                return this.Second_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Second_NameField, value) != true)) {
                    this.Second_NameField = value;
                    this.RaisePropertyChanged("Second_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CityData", Namespace="http://schemas.datacontract.org/2004/07/SMGeoDataContracts")]
    [System.SerializableAttribute()]
    public partial class CityData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Nostradamus8.NostraSrv.CountryData CountryDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Nostradamus8.NostraSrv.StateRegionData StateRegionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TimeDiffField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Nostradamus8.NostraSrv.CountryData CountryData {
            get {
                return this.CountryDataField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryDataField, value) != true)) {
                    this.CountryDataField = value;
                    this.RaisePropertyChanged("CountryData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDCity {
            get {
                return this.IDCityField;
            }
            set {
                if ((this.IDCityField.Equals(value) != true)) {
                    this.IDCityField = value;
                    this.RaisePropertyChanged("IDCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValid {
            get {
                return this.IsValidField;
            }
            set {
                if ((this.IsValidField.Equals(value) != true)) {
                    this.IsValidField = value;
                    this.RaisePropertyChanged("IsValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Nostradamus8.NostraSrv.StateRegionData StateRegionData {
            get {
                return this.StateRegionDataField;
            }
            set {
                if ((object.ReferenceEquals(this.StateRegionDataField, value) != true)) {
                    this.StateRegionDataField = value;
                    this.RaisePropertyChanged("StateRegionData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TimeDiff {
            get {
                return this.TimeDiffField;
            }
            set {
                if ((this.TimeDiffField.Equals(value) != true)) {
                    this.TimeDiffField = value;
                    this.RaisePropertyChanged("TimeDiff");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisplayPersonalRecord", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class DisplayPersonalRecord : Nostradamus8.NostraSrv.PersonalRecordBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataType_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataType_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumEventsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumKWField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumPicturesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Sex_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SourceBirthTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataType_Description {
            get {
                return this.DataType_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DataType_DescriptionField, value) != true)) {
                    this.DataType_DescriptionField = value;
                    this.RaisePropertyChanged("DataType_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataType_Name {
            get {
                return this.DataType_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.DataType_NameField, value) != true)) {
                    this.DataType_NameField = value;
                    this.RaisePropertyChanged("DataType_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAvailable {
            get {
                return this.IsAvailableField;
            }
            set {
                if ((this.IsAvailableField.Equals(value) != true)) {
                    this.IsAvailableField = value;
                    this.RaisePropertyChanged("IsAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumEvents {
            get {
                return this.NumEventsField;
            }
            set {
                if ((this.NumEventsField.Equals(value) != true)) {
                    this.NumEventsField = value;
                    this.RaisePropertyChanged("NumEvents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumKW {
            get {
                return this.NumKWField;
            }
            set {
                if ((this.NumKWField.Equals(value) != true)) {
                    this.NumKWField = value;
                    this.RaisePropertyChanged("NumKW");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumPictures {
            get {
                return this.NumPicturesField;
            }
            set {
                if ((this.NumPicturesField.Equals(value) != true)) {
                    this.NumPicturesField = value;
                    this.RaisePropertyChanged("NumPictures");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex_Description {
            get {
                return this.Sex_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Sex_DescriptionField, value) != true)) {
                    this.Sex_DescriptionField = value;
                    this.RaisePropertyChanged("Sex_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SourceBirthTime {
            get {
                return this.SourceBirthTimeField;
            }
            set {
                if ((this.SourceBirthTimeField.Equals(value) != true)) {
                    this.SourceBirthTimeField = value;
                    this.RaisePropertyChanged("SourceBirthTime");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalRecord", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class PersonalRecord : Nostradamus8.NostraSrv.PersonalRecordBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataType_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataType_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Nostradamus8.NostraSrv.EventData[] EventsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Nostradamus8.NostraSrv.KeyWord[] KeyWordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Nostradamus8.NostraSrv.PersonalNote[] NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Nostradamus8.NostraSrv.PicturesData[] PicturesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Nostradamus8.NostraSrv.Relative[] RelativesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Sex_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SourceBirthTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataType_Description {
            get {
                return this.DataType_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DataType_DescriptionField, value) != true)) {
                    this.DataType_DescriptionField = value;
                    this.RaisePropertyChanged("DataType_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataType_Name {
            get {
                return this.DataType_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.DataType_NameField, value) != true)) {
                    this.DataType_NameField = value;
                    this.RaisePropertyChanged("DataType_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Nostradamus8.NostraSrv.EventData[] Events {
            get {
                return this.EventsField;
            }
            set {
                if ((object.ReferenceEquals(this.EventsField, value) != true)) {
                    this.EventsField = value;
                    this.RaisePropertyChanged("Events");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAvailable {
            get {
                return this.IsAvailableField;
            }
            set {
                if ((this.IsAvailableField.Equals(value) != true)) {
                    this.IsAvailableField = value;
                    this.RaisePropertyChanged("IsAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Nostradamus8.NostraSrv.KeyWord[] KeyWords {
            get {
                return this.KeyWordsField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyWordsField, value) != true)) {
                    this.KeyWordsField = value;
                    this.RaisePropertyChanged("KeyWords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Nostradamus8.NostraSrv.PersonalNote[] Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Nostradamus8.NostraSrv.PicturesData[] Pictures {
            get {
                return this.PicturesField;
            }
            set {
                if ((object.ReferenceEquals(this.PicturesField, value) != true)) {
                    this.PicturesField = value;
                    this.RaisePropertyChanged("Pictures");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Nostradamus8.NostraSrv.Relative[] Relatives {
            get {
                return this.RelativesField;
            }
            set {
                if ((object.ReferenceEquals(this.RelativesField, value) != true)) {
                    this.RelativesField = value;
                    this.RaisePropertyChanged("Relatives");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex_Description {
            get {
                return this.Sex_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Sex_DescriptionField, value) != true)) {
                    this.Sex_DescriptionField = value;
                    this.RaisePropertyChanged("Sex_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SourceBirthTime {
            get {
                return this.SourceBirthTimeField;
            }
            set {
                if ((this.SourceBirthTimeField.Equals(value) != true)) {
                    this.SourceBirthTimeField = value;
                    this.RaisePropertyChanged("SourceBirthTime");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventData", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Nostradamus8.NostraSrv.WorldEventData))]
    public partial class EventData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADV_CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADV_sourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AcessLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthenticityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DataTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DayFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DayToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventStrIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDEventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDEventKindField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_contributorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MonthFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MonthToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlaceEventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceEventNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADV_Category {
            get {
                return this.ADV_CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ADV_CategoryField, value) != true)) {
                    this.ADV_CategoryField = value;
                    this.RaisePropertyChanged("ADV_Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADV_source {
            get {
                return this.ADV_sourceField;
            }
            set {
                if ((object.ReferenceEquals(this.ADV_sourceField, value) != true)) {
                    this.ADV_sourceField = value;
                    this.RaisePropertyChanged("ADV_source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AcessLevel {
            get {
                return this.AcessLevelField;
            }
            set {
                if ((this.AcessLevelField.Equals(value) != true)) {
                    this.AcessLevelField = value;
                    this.RaisePropertyChanged("AcessLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Authenticity {
            get {
                return this.AuthenticityField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticityField, value) != true)) {
                    this.AuthenticityField = value;
                    this.RaisePropertyChanged("Authenticity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryDescription {
            get {
                return this.CategoryDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryDescriptionField, value) != true)) {
                    this.CategoryDescriptionField = value;
                    this.RaisePropertyChanged("CategoryDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DataType {
            get {
                return this.DataTypeField;
            }
            set {
                if ((this.DataTypeField.Equals(value) != true)) {
                    this.DataTypeField = value;
                    this.RaisePropertyChanged("DataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DayFrom {
            get {
                return this.DayFromField;
            }
            set {
                if ((this.DayFromField.Equals(value) != true)) {
                    this.DayFromField = value;
                    this.RaisePropertyChanged("DayFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DayTo {
            get {
                return this.DayToField;
            }
            set {
                if ((this.DayToField.Equals(value) != true)) {
                    this.DayToField = value;
                    this.RaisePropertyChanged("DayTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventDescription {
            get {
                return this.EventDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.EventDescriptionField, value) != true)) {
                    this.EventDescriptionField = value;
                    this.RaisePropertyChanged("EventDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventStrID {
            get {
                return this.EventStrIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EventStrIDField, value) != true)) {
                    this.EventStrIDField = value;
                    this.RaisePropertyChanged("EventStrID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDEvent {
            get {
                return this.IDEventField;
            }
            set {
                if ((this.IDEventField.Equals(value) != true)) {
                    this.IDEventField = value;
                    this.RaisePropertyChanged("IDEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDEventKind {
            get {
                return this.IDEventKindField;
            }
            set {
                if ((this.IDEventKindField.Equals(value) != true)) {
                    this.IDEventKindField = value;
                    this.RaisePropertyChanged("IDEventKind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPerson {
            get {
                return this.IDPersonField;
            }
            set {
                if ((this.IDPersonField.Equals(value) != true)) {
                    this.IDPersonField = value;
                    this.RaisePropertyChanged("IDPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDSource {
            get {
                return this.IDSourceField;
            }
            set {
                if ((this.IDSourceField.Equals(value) != true)) {
                    this.IDSourceField = value;
                    this.RaisePropertyChanged("IDSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_contributor {
            get {
                return this.ID_contributorField;
            }
            set {
                if ((this.ID_contributorField.Equals(value) != true)) {
                    this.ID_contributorField = value;
                    this.RaisePropertyChanged("ID_contributor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MonthFrom {
            get {
                return this.MonthFromField;
            }
            set {
                if ((this.MonthFromField.Equals(value) != true)) {
                    this.MonthFromField = value;
                    this.RaisePropertyChanged("MonthFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MonthTo {
            get {
                return this.MonthToField;
            }
            set {
                if ((this.MonthToField.Equals(value) != true)) {
                    this.MonthToField = value;
                    this.RaisePropertyChanged("MonthTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlaceEvent {
            get {
                return this.PlaceEventField;
            }
            set {
                if ((this.PlaceEventField.Equals(value) != true)) {
                    this.PlaceEventField = value;
                    this.RaisePropertyChanged("PlaceEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlaceEventName {
            get {
                return this.PlaceEventNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceEventNameField, value) != true)) {
                    this.PlaceEventNameField = value;
                    this.RaisePropertyChanged("PlaceEventName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceDescription {
            get {
                return this.SourceDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceDescriptionField, value) != true)) {
                    this.SourceDescriptionField = value;
                    this.RaisePropertyChanged("SourceDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YearFrom {
            get {
                return this.YearFromField;
            }
            set {
                if ((this.YearFromField.Equals(value) != true)) {
                    this.YearFromField = value;
                    this.RaisePropertyChanged("YearFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YearTo {
            get {
                return this.YearToField;
            }
            set {
                if ((this.YearToField.Equals(value) != true)) {
                    this.YearToField = value;
                    this.RaisePropertyChanged("YearTo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyWord", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class KeyWord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADV_KeyWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDKWField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyWordDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReferenceIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADV_KeyWord {
            get {
                return this.ADV_KeyWordField;
            }
            set {
                if ((object.ReferenceEquals(this.ADV_KeyWordField, value) != true)) {
                    this.ADV_KeyWordField = value;
                    this.RaisePropertyChanged("ADV_KeyWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDKW {
            get {
                return this.IDKWField;
            }
            set {
                if ((this.IDKWField.Equals(value) != true)) {
                    this.IDKWField = value;
                    this.RaisePropertyChanged("IDKW");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyWordDescription {
            get {
                return this.KeyWordDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyWordDescriptionField, value) != true)) {
                    this.KeyWordDescriptionField = value;
                    this.RaisePropertyChanged("KeyWordDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReferenceID {
            get {
                return this.ReferenceIDField;
            }
            set {
                if ((this.ReferenceIDField.Equals(value) != true)) {
                    this.ReferenceIDField = value;
                    this.RaisePropertyChanged("ReferenceID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalNote", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class PersonalNote : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ContributorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreation {
            get {
                return this.DateCreationField;
            }
            set {
                if ((this.DateCreationField.Equals(value) != true)) {
                    this.DateCreationField = value;
                    this.RaisePropertyChanged("DateCreation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Contributor {
            get {
                return this.ID_ContributorField;
            }
            set {
                if ((this.ID_ContributorField.Equals(value) != true)) {
                    this.ID_ContributorField = value;
                    this.RaisePropertyChanged("ID_Contributor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PicturesData", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class PicturesData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FileSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDPictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryData {
            get {
                return this.CategoryDataField;
            }
            set {
                if ((this.CategoryDataField.Equals(value) != true)) {
                    this.CategoryDataField = value;
                    this.RaisePropertyChanged("CategoryData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FileSize {
            get {
                return this.FileSizeField;
            }
            set {
                if ((this.FileSizeField.Equals(value) != true)) {
                    this.FileSizeField = value;
                    this.RaisePropertyChanged("FileSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPicture {
            get {
                return this.IDPictureField;
            }
            set {
                if ((this.IDPictureField.Equals(value) != true)) {
                    this.IDPictureField = value;
                    this.RaisePropertyChanged("IDPicture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Reference {
            get {
                return this.ID_ReferenceField;
            }
            set {
                if ((this.ID_ReferenceField.Equals(value) != true)) {
                    this.ID_ReferenceField = value;
                    this.RaisePropertyChanged("ID_Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Relative", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Relative : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionRelationshipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameRelativeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDRelationshipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_RelativeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameRelativeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionRelationship {
            get {
                return this.DescriptionRelationshipField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionRelationshipField, value) != true)) {
                    this.DescriptionRelationshipField = value;
                    this.RaisePropertyChanged("DescriptionRelationship");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstNameRelative {
            get {
                return this.FirstNameRelativeField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameRelativeField, value) != true)) {
                    this.FirstNameRelativeField = value;
                    this.RaisePropertyChanged("FirstNameRelative");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDRelationship {
            get {
                return this.IDRelationshipField;
            }
            set {
                if ((this.IDRelationshipField.Equals(value) != true)) {
                    this.IDRelationshipField = value;
                    this.RaisePropertyChanged("IDRelationship");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Relative {
            get {
                return this.ID_RelativeField;
            }
            set {
                if ((this.ID_RelativeField.Equals(value) != true)) {
                    this.ID_RelativeField = value;
                    this.RaisePropertyChanged("ID_Relative");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastNameRelative {
            get {
                return this.LastNameRelativeField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameRelativeField, value) != true)) {
                    this.LastNameRelativeField = value;
                    this.RaisePropertyChanged("LastNameRelative");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CountryData", Namespace="http://schemas.datacontract.org/2004/07/SMGeoDataContracts")]
    [System.SerializableAttribute()]
    public partial class CountryData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryAcrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryAcr {
            get {
                return this.CountryAcrField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryAcrField, value) != true)) {
                    this.CountryAcrField = value;
                    this.RaisePropertyChanged("CountryAcr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryID {
            get {
                return this.CountryIDField;
            }
            set {
                if ((this.CountryIDField.Equals(value) != true)) {
                    this.CountryIDField = value;
                    this.RaisePropertyChanged("CountryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StateRegionData", Namespace="http://schemas.datacontract.org/2004/07/SMGeoDataContracts")]
    [System.SerializableAttribute()]
    public partial class StateRegionData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateRegionAcrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateRegionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateRegionNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryRef {
            get {
                return this.CountryRefField;
            }
            set {
                if ((this.CountryRefField.Equals(value) != true)) {
                    this.CountryRefField = value;
                    this.RaisePropertyChanged("CountryRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValid {
            get {
                return this.IsValidField;
            }
            set {
                if ((this.IsValidField.Equals(value) != true)) {
                    this.IsValidField = value;
                    this.RaisePropertyChanged("IsValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateRegionAcr {
            get {
                return this.StateRegionAcrField;
            }
            set {
                if ((object.ReferenceEquals(this.StateRegionAcrField, value) != true)) {
                    this.StateRegionAcrField = value;
                    this.RaisePropertyChanged("StateRegionAcr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateRegionID {
            get {
                return this.StateRegionIDField;
            }
            set {
                if ((this.StateRegionIDField.Equals(value) != true)) {
                    this.StateRegionIDField = value;
                    this.RaisePropertyChanged("StateRegionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateRegionName {
            get {
                return this.StateRegionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StateRegionNameField, value) != true)) {
                    this.StateRegionNameField = value;
                    this.RaisePropertyChanged("StateRegionName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorldEventData", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class WorldEventData : Nostradamus8.NostraSrv.EventData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScaleIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScaleID {
            get {
                return this.ScaleIDField;
            }
            set {
                if ((this.ScaleIDField.Equals(value) != true)) {
                    this.ScaleIDField = value;
                    this.RaisePropertyChanged("ScaleID");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NostraSrv.INostraSrv")]
    public interface INostraSrv {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INostraSrv/IsAlive", ReplyAction="http://tempuri.org/INostraSrv/IsAliveResponse")]
        bool IsAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INostraSrv/IsAlive", ReplyAction="http://tempuri.org/INostraSrv/IsAliveResponse")]
        System.Threading.Tasks.Task<bool> IsAliveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INostraSrv/GetCompletePersonalDataById", ReplyAction="http://tempuri.org/INostraSrv/GetCompletePersonalDataByIdResponse")]
        Nostradamus8.NostraSrv.PersonalRecord GetCompletePersonalDataById(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INostraSrv/GetCompletePersonalDataById", ReplyAction="http://tempuri.org/INostraSrv/GetCompletePersonalDataByIdResponse")]
        System.Threading.Tasks.Task<Nostradamus8.NostraSrv.PersonalRecord> GetCompletePersonalDataByIdAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INostraSrvChannel : Nostradamus8.NostraSrv.INostraSrv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NostraSrvClient : System.ServiceModel.ClientBase<Nostradamus8.NostraSrv.INostraSrv>, Nostradamus8.NostraSrv.INostraSrv {
        
        public NostraSrvClient() {
        }
        
        public NostraSrvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NostraSrvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NostraSrvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NostraSrvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsAlive() {
            return base.Channel.IsAlive();
        }
        
        public System.Threading.Tasks.Task<bool> IsAliveAsync() {
            return base.Channel.IsAliveAsync();
        }
        
        public Nostradamus8.NostraSrv.PersonalRecord GetCompletePersonalDataById(int ID) {
            return base.Channel.GetCompletePersonalDataById(ID);
        }
        
        public System.Threading.Tasks.Task<Nostradamus8.NostraSrv.PersonalRecord> GetCompletePersonalDataByIdAsync(int ID) {
            return base.Channel.GetCompletePersonalDataByIdAsync(ID);
        }
    }
}
